theme: jekyll-theme-midnight
title: Allegro & Digit Tactile Sensing Hand Manipulation
Description: Exploring the usage of tactile sensing in hand manipulation. This page exists to provide a general overview of the progression and latest steps of the project.